config/routes.rb
Rails.application.routes.draw do
  get 'contacto', to: 'contacto#index'


  resources :eventos
  resources :lugares

  get '/', to: 'bienvenido#index' 
  post '/', to: 'bienvenido#index'

  root 'bienvenido#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/evento.rb
class Evento < ActiveRecord::Base
	geocoded_by :direccion_completa
	after_validation :geocode

def direccion_completa
self.ubicacion + ", Partido de Lanús, Buenos Aires, Argentina"
end

def marker
{latlng: [self.latitude, self.longitude], popup: self.nombre}
end
end

app/models/lugar.rb
class Lugar < ApplicationRecord
	geocoded_by :direccion_completa
	after_validation :geocode

	def direccion_completa
		self.direccion + ", Partido de Lanús, Buenos Aires, Argentina"
	end

	def marker
		{latlng: [self.latitude, self.longitude], popup: self.nombre}
	end

	def clasificaciones
		["Centro educativo","Centro de salud","Asesor legal integral","Recreación","Deporte y cultura","Comunicación","Centro de jubilados","Ambiente","Negocio"]
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  
end

app/controllers/bienvenido_controller.rb
class BienvenidoController < ApplicationController
  def index
  	
  	# Obtener qué clasificaciones están marcadas
  	@clasificaciones = Lugar.new.clasificaciones
 	@clasificacionesFiltradas = []
  	@clasificaciones.each do |clasificacion|
  		if params[clasificacion] == 'si'
  			@clasificacionesFiltradas << clasificacion
  		end
  	end

  	if @clasificacionesFiltradas.empty?
  		@clasificacionesFiltradas = @clasificaciones
  	end
  	#Filtrar solo los lugares de esas clasificaciones
  	@lugares = Lugar.where(clasificacion: @clasificacionesFiltradas)
  end
end

app/controllers/contacto_controller.rb
class ContactoController < ApplicationController
  def index
  end
  
end

app/controllers/eventos_controller.rb
class EventosController < ApplicationController
	def index
	    @eventos = Evento.order(:fecha).where("fecha >= '"+Time.now.strftime("%Y-%m-%d")+"'")
  	end

	def show
    	@evento = Evento.find(params[:id])
 	end

	def new
	end

	def create
  		@evento = Evento.new(evento_params)
 
 	 	@evento.save
  		redirect_to eventos_path
	end

	def destroy
		@evento = Evento.find(params[:id])
		@evento.destroy

		redirect_to eventos_path
	end	

	def mensaje_de_whatsapp
		URI.encode "whatsapp://send?text=Te invito al evento #{@evento.nombre}!\r\nEl día #{ I18n.localize(@evento.fecha, format: "%A %d de %B, %Y a las %H:%Mhs") }. \r\nEn #{@evento.ubicacion }. \r\n\r\nMás info en #{ request.original_url }"
	end
 
	private
 	
 	def evento_params
    	params.require(:evento).permit(:fecha, :ubicacion, :hora, :nombre, :descripcion)
  	end

end

app/controllers/lugares_controller.rb
class LugaresController < ApplicationController
	def new
    @lugar = Lugar.new
	end

	def create
		@lugar = Lugar.new(lugar_params)
		@lugar.save
		redirect_to @lugar
	end

 	def index
   	@lugares = Lugar.all
 	end
 
 	def show
    @lugar = Lugar.find(params[:id])
 	end

  private
    def lugar_params
      params.require(:lugar).permit(:nombre, :direccion, :clasificacion, :contacto)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bienvenido_helper.rb
module BienvenidoHelper
end

app/helpers/contacto_helper.rb
module ContactoHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/lugares_helper.rb
module LugaresHelper
end

app/views/bienvenido/index.html.erb
<div id="botonera2">
  <%= form_tag '/', method: 'post' do %>
  <ul>
    <% @clasificaciones.each do |clasificacion| -%>
      <li>
        <%= check_box_tag clasificacion, 'si', @clasificacionesFiltradas.include?(clasificacion) %> <%= clasificacion %> 
      </li>
    <% end %>
  </ul>
  <%= submit_tag "Filtrar"%>
  <% end %>
</div>

  <%= map(
    :center => {
      :latlng => [-34.6752, -58.4295],
      :zoom => 16
    }, 
    :markers => @lugares.map { |l| l.marker }
    )%>

<div class="mapa">
  <%= link_to 'Nuevo Lugar', new_lugar_path, class: "boton-nuevo" %>
</div>

app/views/contacto/index.html.erb
<div class="formulario">
	<div class="formulario-contacto">Formulario de contacto:</div>
	    <div class="completar">
			<div class="campo">
				Nombre: 
				<input type="text" name="nombre" size="20" maxlength="60">
			</div>
			<div class="campo"> 
				Correo electronico:
				<input type="text" name="nombre" size="25" maxlength="60">
			</div>
			<div class="campo">
				Asunto: 
				<input type="text" name="nombre" size="35" maxlength="30">
			</div>
			<div class="campo">
				Mensaje:
				<textarea rows="4" cols="20"></textarea>
			</div>

		    <div>
			 <button class="boton" type="submit">Enviar</button>
		    </div>
        </div>
</div>

app/views/eventos/index.html.erb
  <div class="eventos">
  <div id="calendar"> </div>
  <div class="proximos-eventos">   
    <h2>Próximos eventos</h2>   
    <ul>
      <% @eventos.each do |evento| %>
        <li>
          <%= evento.nombre %>
          <%= I18n.localize(evento.fecha, format: "%A %d de %B, %H:%Mhs") %>
          <%= link_to 'Ver', evento_path(evento) %>
        </li>
      <% end %>  
    </ul>
    <%= link_to 'Nuevo Evento', new_evento_path, class: "boton-nuevo" %>
  </div>  
</div>




<script>
$(function() {
  $('#calendar').fullCalendar('destroy');
  $('#calendar').fullCalendar({
    header: {
      left: 'prev,next today',
      center: 'title',
      right: '',
    },
    locale: 'es',
    events: <%= @eventos.map { |m| {title: m.nombre, start: m.fecha } }.to_json.html_safe %>,
    height: 480,
    aspectRatio: 0.2,
    buttonIcons: false, // show the prev/next text
    navLinks: true, // can click day/week names to navigate views
    editable: true,
    eventLimit: true // allow "more" link when too many events
  }); 
});
</script>

app/views/eventos/new.html.erb
<h1 class="nuevo">Nuevo Evento</h1>

<div class="formulario">
<%= form_for :evento, url: eventos_path do |f| %>
  <p>
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </p>

  <p>
    <%= f.label :fecha %><br>
    <%= f.datetime_field :fecha %>
  </p>
 
  <p>
    <%= f.label :ubicacion %><br>
    <%= f.text_area :ubicacion %>
  </p>
 
  <p>
    <%= f.label :descripcion %><br>
    <%= f.text_area :descripcion %>
  </p>

  <p>
    <%= f.submit 'Guardar Evento' %>
  </p>

<% end %>

<div class="volver"><%= link_to 'Volver', eventos_path %></div>

</div>

app/views/eventos/show.html.erb
 <% content_for :og_tags do %>
  <meta property="og:title" content="<%= @evento.nombre %>" />
  <meta property="og:type" content="website" />
  <meta property="og:url" content="<%= request.original_url %>" />
  <meta property="og:image" content="https://static1.ideal.es/www/multimedia/201810/22/media/cortadas/calendario-laboral-festivos-puentes-kaIC-U601318058614N6E-624x385@Ideal.jpg" />
  <meta property="og:image:width" content= "414px" />
  <meta property="og:image:height" content="255px" />
  <meta property="og:description" content= "¡Entrá para conocer más sobre las actividades de tu barrio!" />
  <meta property="fb:app_id" content= "2092342564161138"/>
<% end %>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v3.1';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

   <div class=contenido2>
     <p class="nombre">
       <%= @evento.nombre %>
     </p>

     <p class="fecha">
       <%= I18n.localize(@evento.fecha, format: "%A %d de %B del %Y / %H:%Mhs") %>
     </p>

     <p class="ubicacion">
       <%= @evento.ubicacion %>
     </p>

     <p class="descripcion">
       <%= @evento.descripcion %>
     </p>

     <div id="mapaLugar">
     <%= map(
         :center => {
           :latlng => @evento.marker[:latlng],
           :zoom => 18
         }, 
         :markers => [@evento.marker]
         )%>

     </div>
   </div>

<div class="volver2"><%= link_to 'Volver', eventos_path %></div>
<div class="botones-compartir">
  <div class="div-compartir-whatsapp"> 
    <a class="compartir" href="<%= controller.mensaje_de_whatsapp %>" data-action="share/whatsapp/share">
      <img border="0" alt="W3Schools" src="/logo_whatsapp.png" width="20" height="20"> 
      <div>Compartir</div>
    </a>
  </div>

  <div class="fb-share-button" data-href="<%= request.original_url %>" data-layout="button" data-size="large" data-mobile-iframe="true">
    <a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore" >Compartir</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
      <head>
        <title>Villa Jardín</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
         <link href="https://fonts.googleapis.com/css?family=Nothing+You+Could+Do" rel="stylesheet">
         <link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet">
         <link href="https://fonts.googleapis.com/css?family=Fredericka+the+Great" rel="stylesheet">
         <% if content_for? :og_tags %>
           <%= yield :og_tags %>
         <% end %>
      </head>

      <body>
      <div id="encabezado">
        <div id="titulo">
            <h1>Villa Jardín</h1>
        </div>
        <div id="fecha" es:>
            <h2>
                <%= I18n.localize(Date.today, format: "%A %d %B, %Y") %>
            </h2>

        </div>
        <div id="clima" >
        <div id="TT_FCyEEk11EddNCYwA7AuzDDzDjWnALEIlLYkdkZioaEj" ></div>
        <script type="text/javascript" src="https://www.tutiempo.net/s-widget/l_FCyEEk11EddNCYwA7AuzDDzDjWnALEIlLYkdkZioaEj" width="250px" height="158px"></script>

        </div>
        </div>

        <div id="menu">
            <div id="botonera">
                <ul>
                    <li>
                        <%= link_to 'Nuestro barrio', root_path %>
                    </li>
                    <li>
                        <%= link_to 'Eventos', eventos_path %>
                    </li>
                    <li>
                        <%= link_to 'Contacto', '/contacto/'%>
                    </li>
                    <li>
                </ul>
            </div>
        </div>

        <div id="contenido">
            <%= yield %>
        </div>

        <div id="footer">
            <br>
            <h3>
            <img src="<%= image_url('gmail.png') %>" style="max-width:2.5%;height: auto">
            </img>
            <%= link_to 'redvillajardin@gmail.com', href= "mailto:redvillajardin@gmail.com?__xts__="%></h3>
            <br>
            <h3>
            <img src="<%= image_url('facebook.png') %>" style="max-width:2%;height: auto">
            </img>
            <%= link_to 'Red de Villa Jardin', href= "https://www.facebook.com/redvj/", target:"_blank"%>
            </h3>
        </div>
      </body>

</html>

app/views/lugares/index.html.erb
<h2>Listado de lugares</h2>
 
<%= link_to 'Nuevo Lugar', new_lugar_path %>
 
<table id="tabla" border="0" cellspacing="0" >
  <tr>
    <th>Nombre</th>
    <th>Dirección</th>
    <th>Descripción</th>
    <th>Clasificación</th>
    <th>Contacto</th>
  </tr>
 
  <% @lugares.each do |lugar| %>
    <tr>
      <td><%= lugar.nombre %></td>
      <td><%= lugar.direccion %></td>
      <td><%= lugar.descripcion %></td>
      <td><%= lugar.clasificacion %></td>
      <td><%= lugar.contacto %></td>
    </tr>
  <% end %>
</table>

app/views/lugares/new.html.erb
<div class="formulario">
<%= form_for :lugar, url: lugares_path do |f| %>
  <p>
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </p>

  <p>
    <%= f.label :direccion %><br>
    <%= f.text_field :direccion %>
  </p>

  <p>
    <%= f.label :descripcion %><br>
    <%= f.text_area :descripcion %>
  </p>

  <p>
    <%= f.label :clasificacion %><br>
    <%= f.select(:clasificacion, options_for_select(@lugar.clasificaciones)) %>
  </p>
 
  <p>
    <%= f.label :contacto %><br>
    <%= f.text_field :contacto %>
  </p>
 
 
  <p>
    <%= f.submit 'Guardar' %>
  </p>

<% end %>
</div>

app/views/lugares/show.html.erb
<div class="contenido2">
<p>
  <strong>Nombre:</strong>
  <%= @lugar.nombre %>
</p>
 
<p>
  <strong>Dirección:</strong>
  <%= @lugar.direccion %>
</p>

<p>
  <strong>Descripción:</strong>
  <%= @lugar.descripcion %>
</p>

<p>
  <strong>Clasificación:</strong>
  <%= @lugar.clasificacion %>
</p>

<p>
  <strong>Contacto:</strong>
  <%= @lugar.contacto %>
</p>

<div id="mapaLugar">
<%= map(
    :center => {
      :latlng => @lugar.marker[:latlng],
      :zoom => 18
    }, 
    :markers => [@lugar.marker]
    )%>

</div>
</div>



<%= link_to 'Volver', root_path %>